[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/json"
    X-Content-Type-Options = "nosniff" 