[build]
  command = "npm run build"
  publish = "dist"

# Explicitly handle static files
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = true

[[redirects]]
  from = "/manifest.json"
  to = "/manifest.json"
  status = 200
  force = true

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    X-Content-Type-Options = "nosniff"
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"
    X-Content-Type-Options = "nosniff"
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/json"
    X-Content-Type-Options = "nosniff"
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=3600"

# Default redirect for SPA - this should be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true 