[build]
  command = "npm run build"
  publish = "dist"

# Handle static files directly (no redirects needed)
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    X-Content-Type-Options = "nosniff"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"
    X-Content-Type-Options = "nosniff"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/json"
    X-Content-Type-Options = "nosniff"
    Access-Control-Allow-Origin = "*"

# Default redirect for SPA - this should be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true 